Initialize local variable to silence a clang warning
error: ‘depth’ may be used uninitialized in this function
All enumerators are handled in the switch, so the initial value isn't important.