abi::__forced_unwind is only part of gnu's libstc++.
Summary:
/wrkdirs/usr/ports/databases/akonadi/work/akonadi-17.03.80/src/server/connection.cpp:270:23: error: no type named '__forced_unwind' in namespace '__cxxabiv1'
        } catch (abi::__forced_unwind&) {
                 ~~~~~^
1 error generated.

NPTL is Linux's posix thread implementation, so that exception thrown by it, should only affect the Linux platforms.

Subscribers: #kde_pim

Tags: #kde_pim

Differential Revision: https://phabricator.kde.org/D5168