Add/update CMakeLists for python bindings
The python package must be named KPim6AkonadiCore, or we get this error when trying to import it:
ImportError: dynamic module does not define module export function (PyInit_KPim6AkonadiCorePython)
Since ecm_generate_python_bindings uses the same name for the python package and the target it creates,
The original KPim6AkonadiCore target must be renamed to avoid having multiple targets with the same name