Remove unused included cpp file from autotest.
Summary:
This fixes compilation with cmake git. Otherwise I get:
In file included from akonadi/autotests/libs/actionstatemanagertest.cpp:30:0:
akonadi/src/../src/core/pastehelper.cpp:346:27: fatal error: pastehelper.moc: No such file or directory

Test Plan: make

Reviewers: dvratil

Reviewed By: dvratil

Subscribers: #kde_pim

Tags: #kde_pim

Differential Revision: https://phabricator.kde.org/D4695